/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface OneinchCallerInterface extends utils.Interface {
  functions: {
    "ETH_ADDR()": FunctionFragment;
    "oneInchRouter()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "ETH_ADDR" | "oneInchRouter"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "ETH_ADDR", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "oneInchRouter",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ETH_ADDR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "oneInchRouter",
    data: BytesLike
  ): Result;

  events: {};
}

export interface OneinchCaller extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OneinchCallerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ETH_ADDR(overrides?: CallOverrides): Promise<[string]>;

    oneInchRouter(overrides?: CallOverrides): Promise<[string]>;
  };

  ETH_ADDR(overrides?: CallOverrides): Promise<string>;

  oneInchRouter(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    ETH_ADDR(overrides?: CallOverrides): Promise<string>;

    oneInchRouter(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    ETH_ADDR(overrides?: CallOverrides): Promise<BigNumber>;

    oneInchRouter(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ETH_ADDR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    oneInchRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
