/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICWETHV3,
  ICWETHV3Interface,
} from "../../../../../contracts/interfaces/compound/v3/ICWETHV3";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "borrowBalanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "collateralBalanceOf",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getAssetInfoByAddress",
    outputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "offset",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "address",
            name: "priceFeed",
            type: "address",
          },
          {
            internalType: "uint64",
            name: "scale",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "borrowCollateralFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "liquidateCollateralFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "liquidationFactor",
            type: "uint64",
          },
          {
            internalType: "uint128",
            name: "supplyCap",
            type: "uint128",
          },
        ],
        internalType: "struct ICWETHV3.AssetInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "priceFeed",
        type: "address",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "supply",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICWETHV3__factory {
  static readonly abi = _abi;
  static createInterface(): ICWETHV3Interface {
    return new utils.Interface(_abi) as ICWETHV3Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICWETHV3 {
    return new Contract(address, _abi, signerOrProvider) as ICWETHV3;
  }
}
