/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAggregationExecutor,
  IAggregationExecutorInterface,
} from "../../../../../contracts/interfaces/1inch/IAggregationRouterV5.sol/IAggregationExecutor";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "msgSender",
        type: "address",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IAggregationExecutor__factory {
  static readonly abi = _abi;
  static createInterface(): IAggregationExecutorInterface {
    return new utils.Interface(_abi) as IAggregationExecutorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAggregationExecutor {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IAggregationExecutor;
  }
}
