/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMorphoAaveLens } from "./IMorphoAaveLens";
export type { IMorphoAaveV2 } from "./IMorphoAaveV2";
