/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eventsSol from "./events.sol";
export type { eventsSol };
import type * as proxySol from "./proxy.sol";
export type { proxySol };
