/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAaveOracle,
  IAaveOracleInterface,
} from "../../../../contracts/interfaces/aave/IAaveOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getAssetPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAaveOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IAaveOracleInterface {
    return new utils.Interface(_abi) as IAaveOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAaveOracle {
    return new Contract(address, _abi, signerOrProvider) as IAaveOracle;
  }
}
