/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMorphoAaveLens__factory } from "./IMorphoAaveLens__factory";
export { IMorphoAaveV2__factory } from "./IMorphoAaveV2__factory";
