/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  BasicLogic,
  BasicLogicInterface,
} from "../../../contracts/core/BasicLogic";

const _abi = [
  {
    inputs: [],
    name: "LOGIC_ADDRESS",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class BasicLogic__factory {
  static readonly abi = _abi;
  static createInterface(): BasicLogicInterface {
    return new utils.Interface(_abi) as BasicLogicInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BasicLogic {
    return new Contract(address, _abi, signerOrProvider) as BasicLogic;
  }
}
