/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iAggregationRouterV5Sol from "./IAggregationRouterV5.sol";
export type { iAggregationRouterV5Sol };
