/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILendingLogic,
  ILendingLogicInterface,
} from "../../../../../contracts/main/lendingLogic/base/ILendingLogic";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_protocolId",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "borrow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_protocolId",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_protocolId",
        type: "uint8",
      },
    ],
    name: "enterProtocol",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_protocolId",
        type: "uint8",
      },
    ],
    name: "exitProtocol",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_protocolId",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "getAvailableBorrowsETH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_protocolId",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "getAvailableWithdrawsStETH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "getNetAssetsInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "totalAssets",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalDebt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "netAssets",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "aggregatedRatio",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_protocolId",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "getProtocolAccountData",
    outputs: [
      {
        internalType: "uint256",
        name: "stEthAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "debtEthAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_protocolId",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "getProtocolCollateralRatio",
    outputs: [
      {
        internalType: "uint256",
        name: "ratio",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_protocolId",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_isDepositOrWithdraw",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "_depositOrWithdraw",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_safeRatio",
        type: "uint256",
      },
    ],
    name: "getProtocolLeverageAmount",
    outputs: [
      {
        internalType: "bool",
        name: "isLeverage",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_protocolId",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "repay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "_protocolId",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILendingLogic__factory {
  static readonly abi = _abi;
  static createInterface(): ILendingLogicInterface {
    return new utils.Interface(_abi) as ILendingLogicInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILendingLogic {
    return new Contract(address, _abi, signerOrProvider) as ILendingLogic;
  }
}
