/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BasicLogic__factory } from "./BasicLogic__factory";
export { ILendingLogic__factory } from "./ILendingLogic__factory";
