/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVariableDebtToken,
  IVariableDebtTokenInterface,
} from "../../../../contracts/interfaces/aaveV3/IVariableDebtToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "delegatee",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "approveDelegation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVariableDebtToken__factory {
  static readonly abi = _abi;
  static createInterface(): IVariableDebtTokenInterface {
    return new utils.Interface(_abi) as IVariableDebtTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVariableDebtToken {
    return new Contract(address, _abi, signerOrProvider) as IVariableDebtToken;
  }
}
