/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAaveOracle } from "./IAaveOracle";
export type { IFlashLoanSimpleReceiver } from "./IFlashLoanSimpleReceiver";
export type { IPoolV3 } from "./IPoolV3";
export type { IVariableDebtToken } from "./IVariableDebtToken";
